apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-compute
  namespace: app01-weekend-com
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app01
          image: ghcr.io/phelun/weekend-app01:8cf5e49827dc0ea5257407f995ba468b41884f05