apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-compute
  namespace: app02-weekend-com
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app02
          image: ghcr.io/phelun/weekend-app02:bf4a7fb6de9b3ef4007a25d84afacf9bc57ccf94