apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-compute
  namespace: app02-weekend-com
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app02
          image: ghcr.io/phelun/weekend-app02:c6a4fdbc20a8c82a418acb79cc48aa693a0dc26b