apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-compute
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01-compute
  template:
    metadata:
      labels:
        app: app01-compute
    spec:
      containers:
        - name: app01
          image: ghcr.io/phelun/weekend-app01:48a6cc0cc6039c7ac7c83a9f6c3a2dd8b2937c67
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
