apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03
  namespace: app03-weekend-com
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app03
          image: ghcr.io/phelun/weekend-app03:03ff9bf437feecd488130af70b9cf30dd6a70ef6