apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03
  namespace: app03-weekend-com
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app03
          image: ghcr.io/phelun/weekend-app03:78a96fb668598244cc1c1ffd7784ba2ae29d4e9e